# ???? ??????????
server.port=8081

# ?????? ??? ??????????? ? ?? ? ?????? ?? .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug

# SMTP, ?????? ?? .env
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.protocol=${SMTP_PROTOCOL}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED}
spring.mail.properties.mail.smtp.ssl.trust=${SMTP_SSL_TRUST}

# ???????? ????????? ??? ?????
spring.mail.properties.mail.debug=${SMTP_DEBUG}
